# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/cmake

# The command to remove a file.
RM = /mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /u/sciteam/moradzad/bin/votca/src/csg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /u/sciteam/moradzad/bin/votca/src/csg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/mnt/a/sw/xe_xk_cle5.2UP02_pe2.3.0/bwpy/0.3.0/python-single/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /u/sciteam/moradzad/bin/votca/src/csg/CMakeFiles /u/sciteam/moradzad/bin/votca/src/csg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /u/sciteam/moradzad/bin/votca/src/csg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named uninstall-csg

# Build rule for target.
uninstall-csg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall-csg
.PHONY : uninstall-csg

# fast build rule for target.
uninstall-csg/fast:
	$(MAKE) -f CMakeFiles/uninstall-csg.dir/build.make CMakeFiles/uninstall-csg.dir/build
.PHONY : uninstall-csg/fast

#=============================================================================
# Target rules for targets named manpages

# Build rule for target.
manpages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manpages
.PHONY : manpages

# fast build rule for target.
manpages/fast:
	$(MAKE) -f CMakeFiles/manpages.dir/build.make CMakeFiles/manpages.dir/build
.PHONY : manpages/fast

#=============================================================================
# Target rules for targets named csg_inverse_build

# Build rule for target.
csg_inverse_build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_inverse_build
.PHONY : csg_inverse_build

# fast build rule for target.
csg_inverse_build/fast:
	$(MAKE) -f scripts/CMakeFiles/csg_inverse_build.dir/build.make scripts/CMakeFiles/csg_inverse_build.dir/build
.PHONY : csg_inverse_build/fast

#=============================================================================
# Target rules for targets named csg_call_build

# Build rule for target.
csg_call_build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_call_build
.PHONY : csg_call_build

# fast build rule for target.
csg_call_build/fast:
	$(MAKE) -f scripts/CMakeFiles/csg_call_build.dir/build.make scripts/CMakeFiles/csg_call_build.dir/build
.PHONY : csg_call_build/fast

#=============================================================================
# Target rules for targets named help2t2t_build

# Build rule for target.
help2t2t_build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 help2t2t_build
.PHONY : help2t2t_build

# fast build rule for target.
help2t2t_build/fast:
	$(MAKE) -f scripts/CMakeFiles/help2t2t_build.dir/build.make scripts/CMakeFiles/help2t2t_build.dir/build
.PHONY : help2t2t_build/fast

#=============================================================================
# Target rules for targets named votca_csg

# Build rule for target.
votca_csg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 votca_csg
.PHONY : votca_csg

# fast build rule for target.
votca_csg/fast:
	$(MAKE) -f src/libcsg/CMakeFiles/votca_csg.dir/build.make src/libcsg/CMakeFiles/votca_csg.dir/build
.PHONY : votca_csg/fast

# Manual pre-install relink rule for target.
votca_csg/preinstall:
	$(MAKE) -f src/libcsg/CMakeFiles/votca_csg.dir/build.make src/libcsg/CMakeFiles/votca_csg.dir/preinstall
.PHONY : votca_csg/preinstall

#=============================================================================
# Target rules for targets named gitversion-csg

# Build rule for target.
gitversion-csg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gitversion-csg
.PHONY : gitversion-csg

# fast build rule for target.
gitversion-csg/fast:
	$(MAKE) -f src/libcsg/CMakeFiles/gitversion-csg.dir/build.make src/libcsg/CMakeFiles/gitversion-csg.dir/build
.PHONY : gitversion-csg/fast

#=============================================================================
# Target rules for targets named csg_gmxtopol

# Build rule for target.
csg_gmxtopol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_gmxtopol
.PHONY : csg_gmxtopol

# fast build rule for target.
csg_gmxtopol/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_gmxtopol.dir/build.make src/tools/CMakeFiles/csg_gmxtopol.dir/build
.PHONY : csg_gmxtopol/fast

# Manual pre-install relink rule for target.
csg_gmxtopol/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_gmxtopol.dir/build.make src/tools/CMakeFiles/csg_gmxtopol.dir/preinstall
.PHONY : csg_gmxtopol/preinstall

#=============================================================================
# Target rules for targets named csg_dump

# Build rule for target.
csg_dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_dump
.PHONY : csg_dump

# fast build rule for target.
csg_dump/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_dump.dir/build.make src/tools/CMakeFiles/csg_dump.dir/build
.PHONY : csg_dump/fast

# Manual pre-install relink rule for target.
csg_dump/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_dump.dir/build.make src/tools/CMakeFiles/csg_dump.dir/preinstall
.PHONY : csg_dump/preinstall

#=============================================================================
# Target rules for targets named csg_resample

# Build rule for target.
csg_resample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_resample
.PHONY : csg_resample

# fast build rule for target.
csg_resample/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_resample.dir/build.make src/tools/CMakeFiles/csg_resample.dir/build
.PHONY : csg_resample/fast

# Manual pre-install relink rule for target.
csg_resample/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_resample.dir/build.make src/tools/CMakeFiles/csg_resample.dir/preinstall
.PHONY : csg_resample/preinstall

#=============================================================================
# Target rules for targets named csg_stat

# Build rule for target.
csg_stat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_stat
.PHONY : csg_stat

# fast build rule for target.
csg_stat/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_stat.dir/build.make src/tools/CMakeFiles/csg_stat.dir/build
.PHONY : csg_stat/fast

# Manual pre-install relink rule for target.
csg_stat/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_stat.dir/build.make src/tools/CMakeFiles/csg_stat.dir/preinstall
.PHONY : csg_stat/preinstall

#=============================================================================
# Target rules for targets named csg_reupdate

# Build rule for target.
csg_reupdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_reupdate
.PHONY : csg_reupdate

# fast build rule for target.
csg_reupdate/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_reupdate.dir/build.make src/tools/CMakeFiles/csg_reupdate.dir/build
.PHONY : csg_reupdate/fast

# Manual pre-install relink rule for target.
csg_reupdate/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_reupdate.dir/build.make src/tools/CMakeFiles/csg_reupdate.dir/preinstall
.PHONY : csg_reupdate/preinstall

#=============================================================================
# Target rules for targets named csg_dlptopol

# Build rule for target.
csg_dlptopol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_dlptopol
.PHONY : csg_dlptopol

# fast build rule for target.
csg_dlptopol/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_dlptopol.dir/build.make src/tools/CMakeFiles/csg_dlptopol.dir/build
.PHONY : csg_dlptopol/fast

# Manual pre-install relink rule for target.
csg_dlptopol/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_dlptopol.dir/build.make src/tools/CMakeFiles/csg_dlptopol.dir/preinstall
.PHONY : csg_dlptopol/preinstall

#=============================================================================
# Target rules for targets named csg_property

# Build rule for target.
csg_property: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_property
.PHONY : csg_property

# fast build rule for target.
csg_property/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_property.dir/build.make src/tools/CMakeFiles/csg_property.dir/build
.PHONY : csg_property/fast

# Manual pre-install relink rule for target.
csg_property/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_property.dir/build.make src/tools/CMakeFiles/csg_property.dir/preinstall
.PHONY : csg_property/preinstall

#=============================================================================
# Target rules for targets named csg_fmatch

# Build rule for target.
csg_fmatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_fmatch
.PHONY : csg_fmatch

# fast build rule for target.
csg_fmatch/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_fmatch.dir/build.make src/tools/CMakeFiles/csg_fmatch.dir/build
.PHONY : csg_fmatch/fast

# Manual pre-install relink rule for target.
csg_fmatch/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_fmatch.dir/build.make src/tools/CMakeFiles/csg_fmatch.dir/preinstall
.PHONY : csg_fmatch/preinstall

#=============================================================================
# Target rules for targets named csg_density

# Build rule for target.
csg_density: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_density
.PHONY : csg_density

# fast build rule for target.
csg_density/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_density.dir/build.make src/tools/CMakeFiles/csg_density.dir/build
.PHONY : csg_density/fast

# Manual pre-install relink rule for target.
csg_density/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_density.dir/build.make src/tools/CMakeFiles/csg_density.dir/preinstall
.PHONY : csg_density/preinstall

#=============================================================================
# Target rules for targets named csg_map

# Build rule for target.
csg_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_map
.PHONY : csg_map

# fast build rule for target.
csg_map/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_map.dir/build.make src/tools/CMakeFiles/csg_map.dir/build
.PHONY : csg_map/fast

# Manual pre-install relink rule for target.
csg_map/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_map.dir/build.make src/tools/CMakeFiles/csg_map.dir/preinstall
.PHONY : csg_map/preinstall

#=============================================================================
# Target rules for targets named csg_imcrepack

# Build rule for target.
csg_imcrepack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_imcrepack
.PHONY : csg_imcrepack

# fast build rule for target.
csg_imcrepack/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_imcrepack.dir/build.make src/tools/CMakeFiles/csg_imcrepack.dir/build
.PHONY : csg_imcrepack/fast

# Manual pre-install relink rule for target.
csg_imcrepack/preinstall:
	$(MAKE) -f src/tools/CMakeFiles/csg_imcrepack.dir/build.make src/tools/CMakeFiles/csg_imcrepack.dir/preinstall
.PHONY : csg_imcrepack/preinstall

#=============================================================================
# Target rules for targets named csg_boltzmann

# Build rule for target.
csg_boltzmann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_boltzmann
.PHONY : csg_boltzmann

# fast build rule for target.
csg_boltzmann/fast:
	$(MAKE) -f src/csg_boltzmann/CMakeFiles/csg_boltzmann.dir/build.make src/csg_boltzmann/CMakeFiles/csg_boltzmann.dir/build
.PHONY : csg_boltzmann/fast

# Manual pre-install relink rule for target.
csg_boltzmann/preinstall:
	$(MAKE) -f src/csg_boltzmann/CMakeFiles/csg_boltzmann.dir/build.make src/csg_boltzmann/CMakeFiles/csg_boltzmann.dir/preinstall
.PHONY : csg_boltzmann/preinstall

#=============================================================================
# Target rules for targets named html

# Build rule for target.
html: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 html
.PHONY : html

# fast build rule for target.
html/fast:
	$(MAKE) -f share/doc/CMakeFiles/html.dir/build.make share/doc/CMakeFiles/html.dir/build
.PHONY : html/fast

#=============================================================================
# Target rules for targets named html-csg

# Build rule for target.
html-csg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 html-csg
.PHONY : html-csg

# fast build rule for target.
html-csg/fast:
	$(MAKE) -f share/doc/CMakeFiles/html-csg.dir/build.make share/doc/CMakeFiles/html-csg.dir/build
.PHONY : html-csg/fast

#=============================================================================
# Target rules for targets named template_threaded

# Build rule for target.
template_threaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 template_threaded
.PHONY : template_threaded

# fast build rule for target.
template_threaded/fast:
	$(MAKE) -f share/template/CMakeFiles/template_threaded.dir/build.make share/template/CMakeFiles/template_threaded.dir/build
.PHONY : template_threaded/fast

#=============================================================================
# Target rules for targets named template_serial

# Build rule for target.
template_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 template_serial
.PHONY : template_serial

# fast build rule for target.
template_serial/fast:
	$(MAKE) -f share/template/CMakeFiles/template_serial.dir/build.make share/template/CMakeFiles/template_serial.dir/build
.PHONY : template_serial/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... uninstall"
	@echo "... uninstall-csg"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... manpages"
	@echo "... csg_inverse_build"
	@echo "... csg_call_build"
	@echo "... help2t2t_build"
	@echo "... votca_csg"
	@echo "... gitversion-csg"
	@echo "... csg_gmxtopol"
	@echo "... csg_dump"
	@echo "... csg_resample"
	@echo "... csg_stat"
	@echo "... csg_reupdate"
	@echo "... csg_dlptopol"
	@echo "... csg_property"
	@echo "... csg_fmatch"
	@echo "... csg_density"
	@echo "... csg_map"
	@echo "... csg_imcrepack"
	@echo "... csg_boltzmann"
	@echo "... html"
	@echo "... html-csg"
	@echo "... template_threaded"
	@echo "... template_serial"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

